sudo: required
dist: trusty
language: php
php:
  - "7.1"
python:
  - "3.4"
install:
  - composer require apigen/apigen
  - pip install mkdocs
  - pip install mkdocs-material
  - export PATH=$PATH:./vendor/bin
  - echo hello world
  - git remote -v
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/tunapanda/wp-swag.git

script: ./bin/docs.sh
