sudo: required
dist: trusty
language: php
php:
  - "7.1"
python:
  - "3.4"
#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-4.8
#      - openjdk-7-jdk
install:
  - composer require apigen/apigen
  - pip install mkdocs
  - pip install mkdocs-material
  - export PATH=$PATH:./vendor/bin
  - echo hello world
  - git remote -v
  - git remote set-url origin https://710895255b146e415fc24e05467d9a368b3dbdac@github.com/tunapanda/wp-swag.git

script: ./bin/docs.sh
