site_name: "Tunapanda Swag"
theme: "material"
repo_url: https://github.com/tunapanda/wp-swag
extra_css: []
extra_javascript: []
pages:
- About: index.md
- Motivation:
  - Which challenges does Swag address: challenges.md
  - What makes Swag unique: unique.md
  - Swag from Janet's perspective: janet.md
- Installing: installing.md
- Hacking:
  - Architecture: architecture.md
  - Class docs: classdocs.md
- Join us: join.md